services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  auth-service:
    build:
      context: ./backend
      dockerfile: auth_service/Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/auth_db
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - SERVICE_PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - app-network

  profile-service:
    build:
      context: ./backend
      dockerfile: profile_service/Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/auth_db
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
