services:
  rabbit-mq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - prod-network

  auth-service:
    build:
      context: ./backend
      dockerfile: auth_service/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - prod-network

  profile-service:
    build:
      context: ./backend
      dockerfile: profile_service/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - prod-network

volumes:
  postgres_data:

networks:
  prod-network:
    external: true
    name: prod-network
