"""yandex_id

Revision ID: 0835afb82279
Revises: 8eb8b0f71954
Create Date: 2025-10-18 10:31:45.942544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0835afb82279'
down_revision: Union[str, Sequence[str], None] = '8eb8b0f71954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('yandex_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_auth_users_yandex_id'), 'auth_users', ['yandex_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_users_yandex_id'), table_name='auth_users')
    op.drop_column('auth_users', 'yandex_id')
    # ### end Alembic commands ###
