"""check

Revision ID: 510a3f331f27
Revises: 0835afb82279
Create Date: 2025-10-20 15:18:39.521704

"""
from typing import Sequence, Union




# revision identifiers, used by Alembic.
revision: str = '510a3f331f27'
down_revision: Union[str, Sequence[str], None] = '0835afb82279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
