"""init

Revision ID: ed72875f0fee
Revises: 
Create Date: 2025-10-17 17:25:09.445443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed72875f0fee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('auth_users', sa.Column('vk_id', sa.BigInteger(), nullable=True))
    op.add_column('auth_users', sa.Column('oauth_provider', sa.String(length=20), nullable=True))
    op.alter_column('auth_users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_auth_users_vk_id'), 'auth_users', ['vk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_users_vk_id'), table_name='auth_users')
    op.alter_column('auth_users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('auth_users', 'oauth_provider')
    op.drop_column('auth_users', 'vk_id')
    op.drop_table('items')
    # ### end Alembic commands ###
