name: CI/CD Pipeline

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    
    - name: Analysing the code with pylint
      run: |
        pylint --disable=E0611,E0401,E1101,E1123,W0707,W1203,W0718,W0201,R0903,W0621,C0103,C0301,C0412,C0413,R0801 backend/

  deploy:
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ./deploy
          cp nginx.conf CFDChamp_2025/frontend/
          cp -r ssl/ CFDChamp_2025/frontend/
          cd CFDChamp_2025
          git pull origin main
          docker-compose down
          docker-compose build
          docker-compose up -d
          docker system prune -f
